name: feature_management_experimentation_models
description: Boilerplate for RPC service communication to relay FME flag evaluations
version: 0.0.1+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  dart_mappable: ^4.6.1
  meta: ">=1.15.0 <2.0.0"

dev_dependencies:
  build_runner: ^2.10.5
  dart_mappable_builder: ^4.6.4
  mocktail: ^1.0.4
  test: ^1.29.0
  very_good_analysis: ^10.2.0
