name: api
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0

dependencies:
  dart_frog: ^1.1.0
  dart_frog_web_socket: ^1.0.3
  feature_management_experimentation_models:
    path: ../shared/feature_management_experimentation_models
  very_yummy_coffee_models:
    path: ../shared/very_yummy_coffee_models

dev_dependencies:
  dart_frog_lint: ^0.1.0
  mocktail: ^1.0.3
  test: ^1.25.5
